spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:14.6:///test
    username: test
    password: test
  flyway:
    enabled: true

server:
  port: 8080

documents:
  url: http://localhost:${server.port}/api/documents/
